services:
  mongo:
    image: mongo:8
    container_name: szz-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]

volumes:
  mongo-data:
